
server:
  port: 9901



spring:
  application:
    name: ${spring.cloud.config.name:ytz-service}
  loadbalancer:
    retry:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ytz
    username: root
    password: 123456
  redis:
    host: 172.16.4.160
    port: 6379
    password: 6P%0pvZ$QL
  thymeleaf:
    cache: false
    prefix: classpath:/WEB-INF/pages/
    suffix: .html
    encoding: UTF-8
    mode: HTML5



#mybatis
mybatis:
  mapper_locations: classpath*:mapper/**/**Dao.xml
  type-aliases-package: com.ytz.bean.*
  config-location: classpath:spring/mybatis-config.xml


logging:
  file:
    max-history: 5
    max-size: 10MB
  level:
    com:
      ytz: debug
  config: classpath:config/logback.xml
